# Generated by Django 4.1.5 on 2023-01-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_emision', models.TimeField()),
                ('nombre', models.CharField(max_length=100)),
                ('dias', models.CharField(choices=[('1', 'Lunes a Viernes'), ('2', 'Sabados'), ('3', 'Domingos')], default='Lunes a Viernes', max_length=1)),
            ],
        ),
    ]
