# Generated by Django 4.1.5 on 2023-01-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctv', '0002_alter_programa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='categoria',
            field=models.CharField(choices=[('1', 'Religiosos'), ('2', 'Noticieros'), ('3', 'Analisis'), ('4', 'Familiares'), ('5', 'Entretenimiento')], max_length=1, null=True),
        ),
    ]
