# Generated by Django 4.1.5 on 2023-01-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctv', '0004_noticia_alter_programa_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(null=True, upload_to='noticiasimg'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='idtitulo',
            field=models.CharField(blank=True, editable=False, max_length=200, unique=True),
        ),
    ]
