# Generated by Django 4.1.5 on 2023-02-01 21:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctv', '0005_noticia_imagen_alter_noticia_idtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='idtitulo',
            field=models.CharField(help_text='(Ojo) Colocar el mismo titulo pero sin espacios en blanco utilize guion (-) en vez de espacios en blanco', max_length=200, unique=True),
        ),
    ]
