# Generated by Django 4.1.5 on 2023-02-01 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctv', '0006_noticia_slug_alter_noticia_cuerpo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='idtitulo',
        ),
    ]
